### ISSUE TITLE
Typo in commit title

### ISSUE THREAD

**Issue by Mstrodl** [mralext20/alex-bot#1]
There's a typo in commit [82c2e759bd946e284d1a79aa8c32d34fc8b7514f](https://github.com/mralext20/alex-bot/commit/82c2e759bd946e284d1a79aa8c32d34fc8b7514f)
`safty` -> `safety`

**Comment by tilda** [comment]
gramar polis!! !

**Comment by ArsenArsen** [comment]
this is huge EARTH SHATTERING BUG

pls fix

**Comment by ArsenArsen** [comment]
this is huge EARTH SHATTERING BUG

pls fix

**Comment by xela-zone** [comment]
force pushed.
